### ISSUE TITLE
Auth.SignInAsync fails on iOS simulators after update to 2.4.0-preview 

### ISSUE THREAD

**Issue by klogeaage** [microsoft/appcenter-sdk-dotnet#1130]
### **Description**

After the latest update, I can no longer get the app to work on any of the iOS simulators. It fails in Auth.SignInAsync() with the error  "signIn called while not configured.". 

This happens even though AppCenter.Start() has been called and seems to initialize correctly.

It works fine on real devices, both in debug mode and released. It worked in previous version, however that has a now fixed issue with iOS 13.

### **Repro Steps**

1. Start debug session on iOS simulator with iOS 12.2 or 13.0
2. Call AppCenter.Start() and then Auth.SignInAsync().
3. You just get a white screen and the error Foundation.NSErrorException: Error Domain=com.Microsoft.AppCenter.Auth.ErrorDomain Code=202 "'signIn called while not configured." UserInfo={NSLocalizedDescription='signIn called while not configured.}

### **Details**

1. Xamarin.Forms on iOS.
2. .NET standard 2.0.
2. Which SDK version are you using?
    - 2.4.0 preview, worked on previus preview version
4. Which OS version did you experience the issue on?
    - iOS 12 and 13
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Only on emulators 
6. What third party libraries are you using? 
    - None
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

Launching 'JourneyDoc.iOS' on 'iPhone 11 iOS 13.0'...
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.iOS.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Mono.Security.dll [External]
Resolved pending breakpoint for 'UIKit.UIApplication.Main(System.String[], System.IntPtr, System.IntPtr)' to /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:85 [0x00000].
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/JourneyDoc.iOS.exe
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/JourneyDoc.dll
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.Forms.Platform.iOS.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.Forms.Core.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/netstandard.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Core.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Xml.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Numerics.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Data.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Transactions.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Drawing.Common.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.IO.Compression.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.IO.Compression.FileSystem.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.ComponentModel.Composition.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Net.Http.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Runtime.Serialization.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.ServiceModel.Internals.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Web.Services.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Xml.Linq.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.Forms.Platform.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.Forms.Xaml.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/JourneyDoc.Models.dll
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/JourneyDoc.Common.dll
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Plugin.Permissions.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Plugin.Media.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.IdentityModel.Tokens.Jwt.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.IdentityModel.Tokens.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/System.Security.Cryptography.Cng.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Newtonsoft.Json.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.IdentityModel.Logging.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.IdentityModel.JsonWebTokens.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Auth.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.iOS.Bindings.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Auth.iOS.Bindings.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Analytics.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Analytics.iOS.Bindings.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Crashes.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Microsoft.AppCenter.Crashes.iOS.Bindings.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/Xamarin.Essentials.dll [External]
Loaded assembly: /Users/davidstewart/Library/Developer/CoreSimulator/Devices/768E6256-659F-4760-A716-0FAB1949D05F/data/Containers/Bundle/Application/0F9BB3A1-3E65-4FFD-B6BD-A1A2B13F8BFD/JourneyDoc.iOS.app/OpenTK-1.0.dll [External]
[HotReload] (2019-09-27 09:55:05.0): INFO: Hot Reload Initializing...
Loaded assembly: data-0x10b0d1000 [External]
Loaded assembly: data-0x7fb2cccd0e00 [External]
Loaded assembly: data-0x111384000 [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to [0x0](no debug symbols).
Thread started:  #2
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System/Object.cs:74 [0x00000].
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System/Object.cs:82 [0x00000].
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System/Object.cs:90 [0x00000].
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System/Object.cs:114 [0x00000].
2019-09-27 09:55:09.545916+0200 JourneyDoc.iOS[68524:1576958] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68524
2019-09-27 09:55:09.546244+0200 JourneyDoc.iOS[68524:1576958] SecTaskCopyDebugDescription: JourneyDoc.iOS[68524]/0#-1 LF=0
2019-09-27 09:55:09.557810+0200 JourneyDoc.iOS[68524:1576958] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68524
2019-09-27 09:55:09.558098+0200 JourneyDoc.iOS[68524:1576958] SecTaskCopyDebugDescription: JourneyDoc.iOS[68524]/0#-1 LF=0
Resolved pending breakpoint at 'App.xaml.cs:49,1' to void JourneyDoc.App.OnStart () [0x00040].
2019-09-27 09:55:10.482473+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSDelegateForwarder addTraceBlock:]_block_invoke_2/88 Start buffering traces.
2019-09-27 09:55:10.482698+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/278 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
2019-09-27 09:55:10.482886+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSDelegateForwarder swizzleOriginalSelector:withCustomSelector:originalClass:]_block_invoke/205 Selector 'setDelegate:' of class 'UIApplication' is swizzled.
2019-09-27 09:55:10.483054+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSDelegateForwarder swizzleOriginalSelector:withCustomSelector:originalClass:]_block_invoke/205 Selector 'application:openURL:options:' of class 'AppDelegate' is swizzled.
2019-09-27 09:55:10.483226+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: +[MSDelegateForwarder flushTraceBuffer]/106 Stop buffering traces, flushed.
2019-09-27 09:55:10.511459+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSSessionContext init]/42 1 session(s) in the history.
2019-09-27 09:55:10.513827+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/66 Stored new session with id:(null) and timestamp: 2019-09-27 07:55:10 +0000.
2019-09-27 09:55:10.514230+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSUserIdContext init]/54 1 userId(s) in the history.
2019-09-27 09:55:10.516462+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.517214+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.517372+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.517606+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] DEBUG: -[MSDBStorage initWithSchema:version:filename:]_block_invoke/29 SQLite global configuration successfully updated.
2019-09-27 09:55:10.520876+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/292 App Center SDK configured successfully.
2019-09-27 09:55:10.521599+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/318 Start services MSCrashes, MSAnalytics, MSAuth from an application
2019-09-27 09:55:10.525551+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/634 EnableUncaughtExceptionHandler is set to NO, we're running in a Xamarin runtime.
2019-09-27 09:55:10.537821+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/677 Exception handler successfully initialized but it has not been registered due to the wrapper SDK.
2019-09-27 09:55:10.540429+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSSessionContext clearSessionHistoryAndKeepCurrentSession:]/88 Cleared old sessions.
2019-09-27 09:55:10.541133+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSUserIdContext clearUserIdHistory]/124 Cleared old userIds while keeping current userId.
2019-09-27 09:55:10.541285+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] INFO: -[MSCrashes applyEnabledState:]/389 Crashes service has been enabled.
2019-09-27 09:55:10.548952+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/434 Started crash service.
2019-09-27 09:55:10.549512+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/551 Identifying object <MSAnalytics: 0x6000008b6f40> removed from pause lane for channel Analytics.
2019-09-27 09:55:10.549706+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/553 Resume channel Analytics.
2019-09-27 09:55:10.549958+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/551 Identifying object <MSAnalytics: 0x6000008b6f40> removed from pause lane for channel Analytics/one.
2019-09-27 09:55:10.550148+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/553 Resume channel Analytics/one.
2019-09-27 09:55:10.550227+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/66 Stored new session with id:DE5768B6-EC87-4A9B-82CF-ACA92BC2535C and timestamp: 2019-09-27 07:55:10 +0000.
2019-09-27 09:55:10.550398+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAnalytics] INFO: -[MSSessionTracker renewSessionId]/49 New session ID: DE5768B6-EC87-4A9B-82CF-ACA92BC2535C
2019-09-27 09:55:10.556033+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.556285+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.556561+0200 JourneyDoc.iOS[68524:1576958] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.557326+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.557533+0200 JourneyDoc.iOS[68524:1576958] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.558161+0200 JourneyDoc.iOS[68524:1576958] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.558221+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.560065+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.560381+0200 JourneyDoc.iOS[68524:1577030] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-27 09:55:10.560835+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/511 Storing a log to Crashes Buffer: (sid: DE5768B6-EC87-4A9B-82CF-ACA92BC2535C, type: startSession)
2019-09-27 09:55:10.561018+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/522 Found an empty buffer position.
2019-09-27 09:55:10.561291+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAnalytics] INFO: -[MSAnalytics applyEnabledState:]/155 Analytics service has been enabled.
2019-09-27 09:55:10.561298+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/187 Saving log, type: startSession, flags: 1.
2019-09-27 09:55:10.561577+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAnalytics] VERBOSE: -[MSAnalytics startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/107 Started Analytics service.
2019-09-27 09:55:10.564928+0200 JourneyDoc.iOS[68524:1577030] [AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/120 Log is stored with id: '12'
2019-09-27 09:55:10.565366+0200 JourneyDoc.iOS[68524:1577030] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/564 Deleting a log from buffer with id 9735A287-A2EA-494D-A54B-7D4C70FDCDFD
2019-09-27 09:55:10.566992+0200 JourneyDoc.iOS[68524:1577030] [AppCenterAuth] ERROR: -[MSAuth startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]_block_invoke/91 TID=1576958 MSAL 0.7.0 iOS Sim 13.0 [2019-09-27 07:55:10] Encountered an error when reading teamIDHint in keychain. Keychain status -34018, read status -25300
2019-09-27 09:55:10.567265+0200 JourneyDoc.iOS[68524:1577030] [AppCenterAuth] INFO: -[MSAuth startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]_block_invoke/87 TID=1576958 MSAL 0.7.0 iOS Sim 13.0 [2019-09-27 07:55:10] Using "Masked(null)" Team ID.
2019-09-27 09:55:10.567498+0200 JourneyDoc.iOS[68524:1577030] [AppCenterAuth] ERROR: -[MSAuth startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]_block_invoke/91 TID=1576958 MSAL 0.7.0 iOS Sim 13.0 [2019-09-27 07:55:10] Failed to retrieve teamId from keychain.
2019-09-27 09:55:10.568709+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] ERROR: -[MSAuth configAuthenticationClient]/409 Failed to initialize client application: The operation couldn’t be completed. (MSALErrorDomain error -50000.)
2019-09-27 09:55:10.569342+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.569528+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.569903+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/362 Internet connection is up.
2019-09-27 09:55:10.570363+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] VERBOSE: -[MSAuthConfigIngestion createRequest:eTag:authToken:]/50 URL: https://config.appcenter.ms/auth/****************************4233b3bd.json
2019-09-27 09:55:10.570640+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] VERBOSE: -[MSAuthConfigIngestion createRequest:eTag:authToken:]/52 Headers: If-None-Match = 0x8D73D3D41DB2AFB
2019-09-27 09:55:10.571324+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] INFO: -[MSAuth applyEnabledState:]/144 Auth service has been enabled.
2019-09-27 09:55:10.571490+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] VERBOSE: -[MSAuth startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/102 Started Auth service.
2019-09-27 09:55:10.572253+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/511 Storing a log to Crashes Buffer: (sid: (null), type: startService)
2019-09-27 09:55:10.572441+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/522 Found an empty buffer position.
2019-09-27 09:55:10.572766+0200 JourneyDoc.iOS[68524:1577050] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/187 Saving log, type: startService, flags: 1.
2019-09-27 09:55:10.575880+0200 JourneyDoc.iOS[68524:1577050] [AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/120 Log is stored with id: '13'
2019-09-27 09:55:10.576375+0200 JourneyDoc.iOS[68524:1577050] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/564 Deleting a log from buffer with id 4A4378A8-1739-41DC-BC77-BAB51CA64699
2019-09-27 09:55:10.589024+0200 JourneyDoc.iOS[68524:1577062] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68524
2019-09-27 09:55:10.589374+0200 JourneyDoc.iOS[68524:1577062] SecTaskCopyDebugDescription: JourneyDoc.iOS[68524]/0#-1 LF=0
2019-09-27 09:55:10.752712+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/262 HTTP response received with status code: 304, payload:
(null)
2019-09-27 09:55:10.752903+0200 JourneyDoc.iOS[68524:1577062] [AppCenterAuth] INFO: -[MSAuth downloadConfigurationWithETag:]_block_invoke/344 Auth config hasn't changed.
2019-09-27 09:55:10.753090+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] INFO: -[MSHttpIngestion pause]/163 Pause ingestion.
2019-09-27 09:55:10.753329+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/311 Removed call id:8CE53CB9-092C-4A6B-86D7-491363A475D9 from pending calls:{
}
2019-09-27 09:55:10.761750+0200 JourneyDoc.iOS[68524:1577062] [] nw_connection_receive_internal_block_invoke [C1] Receive reply failed with error "Operation canceled"
2019-09-27 09:55:10.761960+0200 JourneyDoc.iOS[68524:1577062] [] nw_connection_receive_internal_block_invoke [C1] Receive reply failed with error "Operation canceled"
2019-09-27 09:55:10.762131+0200 JourneyDoc.iOS[68524:1577062] [] nw_connection_receive_internal_block_invoke [C1] Receive reply failed with error "Operation canceled"
2019-09-27 09:55:10.76
2440+0200 JourneyDoc.iOS[68524:1577062] [] nw_connection_receive_internal_block_invoke [C1] Receive reply failed with error "Operation canceled"
2019-09-27 09:55:13.828301+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] WARNING: -[MSAuthTokenContext authTokenHistory]/210 Failed to retrieve history state or none was found.
2019-09-27 09:55:13.830310+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:afterDate:beforeDate:completionHandler:]/212 Load log(s) with id(s) '12' as batch Id:C8233756-4999-4266-AD6B-45391F7A12C8
2019-09-27 09:55:13.831431+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]/224 Sending 1/1 log, group Id: Analytics, batch Id: C8233756-4999-4266-AD6B-45391F7A12C8, session Id: DE5768B6-EC87-4A9B-82CF-ACA92BC2535C, payload:
{
  "sid" : "DE5768B6-EC87-4A9B-82CF-ACA92BC2535C",
  "timestamp" : "2019-09-27T07:55:10.551Z",
  "device" : {
    "appVersion" : "0.1",
    "appBuild" : "1",
    "osName" : "iOS",
    "timeZoneOffset" : 120,
    "wrapperSdkVersion" : "2.4.0",
    "osVersion" : "13.0",
    "wrapperRuntimeVersion" : "11.14.0",
    "locale" : "en_US",
    "wrapperSdkName" : "appcenter.xamarin",
    "appNamespace" : "com.companyname.JourneyDoc",
    "osBuild" : "18G95",

    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "sdkVersion" : "2.4.0",
    "model" : "x86_64",
    "screenSize" : "1792x828"
  },
  "type" : "startSession"
}
2019-09-27 09:55:13.832229+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/91 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2019-09-27 09:55:13.832519+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/92 Headers: Install-ID = FC216139-E80D-40F2-A700-92E378275284, App-Secret = ****************************4233b3bd, Content-Type = application/json
2019-09-27 09:55:13.834681+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:afterDate:beforeDate:completionHandler:]/212 Load log(s) with id(s) '13' as batch Id:3081F830-D303-4AE4-9C33-76F831531BC3
2019-09-27 09:55:13.835203+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]/224 Sending 1/1 log, group Id: AppCenter, batch Id: 3081F830-D303-4AE4-9C33-76F831531BC3, session Id: (null), payload:
{
  "device" : {
    "appVersion" : "0.1",
    "appBuild" : "1",
    "osName" : "iOS",
    "timeZoneOffset" : 120,
    "wrapperSdkVersion" : "2.4.0",
    "osVersion" : "13.0",
    "wrapperRuntimeVersion" : "11.14.0",
    "locale" : "en_US",
    "wrapperSdkName" : "appcenter.xamarin",
    "appNamespace" : "com.companyname.JourneyDoc",
    "osBuild" : "18G95",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "sdkVersion" : "2.4.0",
    "model" : "x86_64",
    "screenSize" : "1792x828"
  },
  "timestamp" : "2019-09-27T07:55:10.572Z",
  "type" : "startService",
  "services" : [
    "Crashes",
    "Analytics",
    "Auth"
  ]
}
2019-09-27 09:55:13.835759+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/91 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2019-09-27 09:55:13.836152+0200 JourneyDoc.iOS[68524:1577062] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/92 Headers: Install-ID = FC216139-E80D-40F2-A700-92E378275284, App-Secret = ****************************4233b3bd, Content-Type = application/json
2019-09-27 09:55:15.120635+0200 JourneyDoc.iOS[68524:1577057] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/262 HTTP response received with status code: 200, payload:
CorrelationId: b265b4f5-4423-4772-9e74-624763bd1366  ReasonCode: Success
2019-09-27 09:55:15.121004+0200 JourneyDoc.iOS[68524:1577059] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]_block_invoke/247 Log(s) sent with success, batch Id:C8233756-4999-4266-AD6B-45391F7A12C8.
2019-09-27 09:55:15.121060+0200 JourneyDoc.iOS[68524:1577057] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/311 Removed call id:C8233756-4999-4266-AD6B-45391F7A12C8 from pending calls:{
    "3081F830-D303-4AE4-9C33-76F831531BC3" = "<MSIngestionCall: 0x600001e23000>";
}
2019-09-27 09:55:15.130154+0200 JourneyDoc.iOS[68524:1577059] [AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/353 Deletion of log(s) by id with value(s) '12' succeeded.
2019-09-27 09:55:15.183800+0200 JourneyDoc.iOS[68524:1577036] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/262 HTTP response received with status code: 200, payload:
CorrelationId: 9afe35da-c282-4627-a518-9d235c965df0  ReasonCode: Success
2019-09-27 09:55:15.184122+0200 JourneyDoc.iOS[68524:1577036] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/311 Removed call id:3081F830-D303-4AE4-9C33-76F831531BC3 from pending calls:{
}
2019-09-27 09:55:15.184126+0200 JourneyDoc.iOS[68524:1577050] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]_block_invoke/247 Log(s) sent with success, batch Id:3081F830-D303-4AE4-9C33-76F831531BC3.
2019-09-27 09:55:15.186880+0200 JourneyDoc.iOS[68524:1577050] [AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/353 Deletion of log(s) by id with value(s) '13' succeeded.
Resolved pending breakpoint at 'SignedInUserViewModel.cs:54,1' to void JourneyDoc.ViewModels.SignedInUserViewModel.<SignInAsync>d__12.MoveNext () [0x00177].
[HotReload] (2019-09-27 09:55:09.3): INFO: HotReload: Initialized Agent.
[HotReload] (2019-09-27 09:57:02.4): INFO: Hot Reload Connected and Ready.
2019-09-27 09:57:03.788651+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/511 Storing a log to Crashes Buffer: (sid: DE5768B6-EC87-4A9B-82CF-ACA92BC2535C, type: handledError)
2019-09-27 09:57:03.788913+0200 JourneyDoc.iOS[68524:1576958] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/522 Found an empty buffer position.
2019-09-27 09:57:03.789211+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/187 Saving log, type: handledError, flags: 1.
2019-09-27 09:57:03.789628+0200 JourneyDoc.iOS[68524:1576958] [AppCenterAuth] WARNING: -[MSAuth clearAuthData]/435 Couldn't remove account data.
2019-09-27 09:57:03.789842+0200 JourneyDoc.iOS[68524:1576958] [AppCenter] WARNING: -[MSAuthTokenContext setAuthTokenHistory:]/225 Failed to save new history state.
2019-09-27 09:57:03.792214+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/120 Log is stored with id: '14'
2019-09-27 09:57:03.792626+0200 JourneyDoc.iOS[68524:1577371] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/564 Deleting a log from buffer with id E729340D-C2B4-4306-89FC-79AEEAF40F24
2019-09-27 09:57:03.792875+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793057+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793229+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793397+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793547+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793725+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.793875+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.794024+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.794196+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.794367+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.794648+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:03.794982+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] INFO: -[MSChannelUnitDefault authTokenContext:didUpdateAuthToken:]_block_invoke/105 New auth token received, flushing queue.
2019-09-27 09:57:05.295819+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:afterDate:beforeDate:completionHandler:]/212 Load log(s) with id(s) '14' as batch Id:787D7BDC-AD6F-468C-A965-2067FC3429D4
2019-09-27 09:57:05.296481+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]/224 Sending 1/1 log, group Id: Crashes, batch Id: 787D7BDC-AD6F-468C-A965-2067FC3429D4, session Id: DE5768B6-EC87-4A9B-82CF-ACA92BC2535C, payload:
{
  "sid" : "DE5768B6-EC87-4A9B-82CF-ACA92BC2535C",
  "timestamp" : "2019-09-27T07:57:03.788Z",
  "device" : {
    "appVersion" : "0.1",
    "appBuild" : "1",
    "osName" : "iOS",
    "timeZoneOffset" : 120,
    "wrapperSdkVersion" : "2.4.0",
    "osVersion" : "13.0",
    "wrapperRuntimeVersion" : "11.14.0",
    "locale" : "en_US",
    "wrapperSdkName" : "appcenter.xamarin",
    "appNamespace" : "com.companyname.JourneyDoc",
    "osBuild" : "18G95",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "sdkVersion" : "2.4.0",
    "model" : "x86_64",
    "screenSize" : "1792x828"
  },
  "type" : "handledError",
  "id" : "85053CCC-AB6D-44DC-A683-E11C9BAEF44A",
  "exception" : {
    "message" : "Error Domain
=com.Microsoft.AppCenter.Auth.ErrorDomain Code=202 \"'signIn called while not configured.\" UserInfo={NSLocalizedDescription='signIn called while not configured.}",
    "wrapperSdkName" : "appcenter.xamarin",
    "type" : "Foundation.NSErrorException",
    "stackTrace" : "  at JourneyDoc.ViewModels.SignedInUserViewModel.SignInAsync () [0x00045] in D:\\Source\\Repos\\JourneyDoc\\JourneyDoc\\ViewModels\\SignedInUserViewModel.cs:50 "
  }
}
2019-09-27 09:57:05.297395+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/91 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2019-09-27 09:57:05.297730+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:eTag:authToken:]/92 Headers: Install-ID = FC216139-E80D-40F2-A700-92E378275284, App-Secret = ****************************4233b3bd, Content-Type = application/json
2019-09-27 09:57:05.823503+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/262 HTTP response received with status code: 200, payload:
CorrelationId: 1c268544-488d-4b40-85cc-6ee4b8a65b22  ReasonCode: Success
2019-09-27 09:57:05.823779+0200 JourneyDoc.iOS[68524:1577642] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/311 Removed call id:787D7BDC-AD6F-468C-A965-2067FC3429D4 from pending calls:{
}
2019-09-27 09:57:05.823913+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]_block_invoke/247 Log(s) sent with success, batch Id:787D7BDC-AD6F-468C-A965-2067FC3429D4.
2019-09-27 09:57:05.833477+0200 JourneyDoc.iOS[68524:1577371] [AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/353 Deletion of log(s) by id with value(s) '14' succeeded.

**Comment by annakocheshkova** [comment]
Hey, pretty strange, have you changed the app secret or anything else after migration? Could you try cleaning the app data (or even better, removing and installing it again)?

**Comment by klogeaage** [comment]
Nope, nothing has changed except upgrading. I have tried deleting the app form the simulator with no effect.

**Comment by annakocheshkova** [comment]
I see the following error in your logs which might be related: "Failed to retrieve teamId from 
I sets "null" for teamID.
This can mean improper keychain setup for iPhone distribution. Could you make sure you have the certificate with the nested key?

**Comment by klogeaage** [comment]
Hi Anna, 
I had been using automatic provisioning but now I tried switching to manual and add the existing Entitlements.plist as (which had the keychain values set already) as a Custom Entitlement as specified in [this article](https://forums.xamarin.com/discussion/122847/keychain-access-on-ios-11-simulator-requires). And lo and behold, now it works again. 

I can see that doing this added 

`<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>`

to the iOS project file. I wonder why that was not picked up by the automatic provisioning? Is the conclusion that you cannot use automatic provisioning if you need keychain support, i.e. you cannot use it with AppCenter.Auth?

Anyway, thank you very much, my problem is solved 😊.

**Comment by annakocheshkova** [comment]
Not sure why, but I've read somewhere that you need to manually specify it in project settings.
Ok glad the issue is resolved, closing this one!

**Comment by supreettare** [comment]
Hey Guys, 
I am still facing this exact same issue on iOS both on Simulator & on real device. I've setup the info.plist, updated entitlments.plist & am using manual build with the entitlement.plist file included. 
I am still getting the following error: 
"Error Domain=com.Microsoft.AppCenter.Auth.ErrorDomain Code=202 "'signIn called while not configured." UserInfo={NSLocalizedDescription='signIn called while not configured.}"

Can you help me point out to something I am missing please?

Regards
ST

**Comment by guperrot** [comment]
@supreettare can you create a new issue and follow the template? It's probably something different and we will need SDK logs.

**Comment by supreettare** [comment]
Hi @guperrot Thanks for your response. Really appreciate it. This was resolved after updating the Auth libraries from 2.1.1 to 2.5.0 
Apologies for not seeing this before.

**Comment by guperrot** [comment]
No problem, it can be challenging to stay up-to-date with all dependencies in a project.
