### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by EatonZ** [microsoft/appcenter-sdk-dotnet#1361]
### **Description**

I am seeing these happen frequently:

`[AppCenter] ERROR: Sending logs for channel 'core', batch 'REDACTED' failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

`ERROR: Sending logs for channel 'analytics', batch 'REDACTED' failed: The SSL connection could not be established, see inner exception.`

`WARN: Channel is disabled; logs are discarded`

I'm not sure if it's due to an SDK bug, or if your server is just being slow due to being overwhelmed. I still wanted to report it because I do see these frequently.

### **Repro Steps**

Unfortunately, there is no reliable way to reproduce this.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WinForms
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - NET Core  3.1
2. Which SDK version are you using?
    - 3.1.0
4. Which OS version did you experience the issue on?
    - Windows 10 1903 64bit
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical desktop PC

**Comment by AnastasiaKubova** [comment]
Hi, @EatonZ ! Thanks for getting in touch with us! Unfortunately, I can't reproduce this issue. 
Could you please clarify some details:
- Can you see any logs on the portal from your app?
- Have you a chance to share the verbose [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/wpf-winforms#adjust-the-log-level) with inner exception?

**Comment by EatonZ** [comment]
@AnastasiaKubova Yes, stuff does show up, but I'm concerned some things aren't coming in from my users because of this error.

This doesn't happen often and I don't have that enabled when it does, so it's hard to get them. I think this is a server issue though - anything going on there lately?

**Comment by MatkovIvan** [comment]
Hi @EatonZ ,

Could you please share full log and the time when it happened? It will help us narrow down the problem.

**Comment by EatonZ** [comment]
I will post more details if/when I notice it happens again.

**Comment by EatonZ** [comment]
@MatkovIvan @AnastasiaKubova Here is the output with verbose logging:

![2020-04-05_13-31-54](https://user-images.githubusercontent.com/3020941/78505505-dd717000-7741-11ea-8518-b58fa6c83c93.png)

**Comment by MatkovIvan** [comment]
It looks like just timeout due to network issues, but SDK should do retry after this network exception. I'm marking this issue as a bug because of that. We'll investigate why retry logic is not work in this case.

**Comment by MatkovIvan** [comment]
> I think this is a server issue though - anything going on there lately?

Yes, there were some issues on backend. It is already captured, so this should work now.

**Comment by EatonZ** [comment]
Just had it happen again, so maybe it's not fully resolved on the backend.

**Comment by EatonZ** [comment]
I also saw this, but I've only seen this message once:
`2020-04-11 17:35:15.217 [AppCenter] WARN: Try #1 failed and will be retried in 9016 ms`

So it seems like there indeed may be something wrong with retries since this is the first time I've seen that message.

**Comment by annakocheshkova** [comment]
Hey @EatonZ this message is ok, it means sending logs **will** be retried. This is not related to the original issue.

**Comment by olmisa** [comment]
@EatonZ version 3.2.1 which contains a fix was released.
