### ISSUE TITLE
Self-contained .NET 5.0 apps do not send data to AppCenter

### ISSUE THREAD

**Issue by anti-matter** [microsoft/appcenter-sdk-dotnet#1483]
### **Description**

Self-contained .net 5.0 apps do not send data to AppCenter. This worked fine when building with .NET Core 3.1 with same app. After upgrading .NET SDK to 5.0, events are no longer sent to AppCenter.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a .NET 5.0 app and include AppCenter NuGet SDK package - do normal AppCenter SDK initialization
2. Publish the app and have it built as a _**self-contained**_ file
3. Run the app. Observe that events fail to send to AppCenter with the following debug output:

ModLoad: 00007ffe768f0000 00007ffe76a2b000   C:\Users\micha\AppData\Local\Temp\.net\Cloudflare WARP\5dj5hccl.fe0\e_sqlite3.DLL
2020-12-23 14:26:38.363 [AppCenter] WARN: Configuration is corrupted. App Center could work incorrectly. Method 'GetValue', key:AppCenterServiceEnabled_analytics
2020-12-23 14:26:38.364 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2020-12-23 14:26:38.365 [AppCenter] WARN: Configuration is corrupted. App Center could work incorrectly. Method 'GetValue', key:AppCenterCrashesAlwaysSend

### **Details**

1. Platform: NET 5.0 WPF Windows desktop application
2. SDK version: 4.0.0

**NOTE**: if I run app from Visual Studio directly, it reports successfully to AppCenter.

**Comment by Mgamerz** [comment]
From my previous experience with appcenter not working, it's likely to do with sqlite. It seems to really hate not being right next to the executable.

**Comment by EatonZ** [comment]
Just add it to the pile of sqlite issues https://github.com/microsoft/appcenter-sdk-dotnet/issues/1354

**Comment by DmitriyKirakosyan** [comment]
Hi @anti-matter,

Thanks for getting in touch with us!
We will investigate this issue and get back to you with an update.

@EatonZ Thank you for following the repo and reminding about the SQLite removal feature request!

**Comment by anti-matter** [comment]
I'm really hoping for a work-around. We have an app in production that needs updating, but we can't update it until we can figure out a work-around to this issue. I've tried a couple of the other linked work-arounds, but they did not work.

**Comment by AnastasiaKubova** [comment]
Please try to use [this property](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#optional-settings) `IncludeAllContentForSelfExtract` in your publish profiler.
Also, could you please clarify does it happen with App Center only or this affects the work of other libraries too?

**Comment by anti-matter** [comment]
@AnastasiaKubova thank you, including that property got me past the issue I was encountering. Much appreciated!

**Comment by AnastasiaKubova** [comment]
Glad to hear that your problem was resolved. 
Thanks for using the App Center.

**Comment by Mgamerz** [comment]
Is this going to be fixed so it doesn't require this?

**Comment by AnastasiaKubova** [comment]
@Mgamerz could you please clarify does it happen with App Center only or this affects the work of other libraries too?

**Comment by Mgamerz** [comment]
This issue only appears to be affecting app center. As app center is closed
source no way to look into why. I know .net 5 has single file breaking
changes.

When I packaged my app on .net 5, which had 15 or so libraries (a few
native and many .net), all of them appeared to work (all my tests worked,
all my actual usage of all worked). Pretty much everything looked fine
until I tried to give my published single file exe to users for testing. I
waited a week wondering why nothing was coming in and it turns out it's
cause appcenter packaged as single file with the native libraries option
doesn't work on .net 5.

It seems appcenter does not work with .net 5 single file unless you turn on
backwards compatibility flags (do the single file is island like .net core
3.1), but it feels like it shouldn't since both .net5 and appcenter are
made by the same (large) company (nor was this documented anywhere on app
center documentation).

I know .net 5 is still somewhat new but that's why I'm asking if this is
going to be fixed? One of the big reasons I don't want to have to turn on
this flag is because there are a lot of improvements to single file apps in
.net 5, such as not having to extract everything from the exe, but only
native libs. I get telemetry from app center on .netcore3.1 that indicates
my app is crashing due to windows deleting the temp directory, and the.net
5 for the most part appeared to solve this issue with my testers.

Having to turn in backwards compat seems like it just makes you lose
benefits that come with.net 5. Another product also made by Microsoft.

**Comment by anti-matter** [comment]
I was just about to reply myself as I realized that the property IncludeAllContentForSelfExtract does indeed make the .NET 5.0 single-file behave like .NET 3.1. The ONLY reason we are moving to .NET 5.0 was to get rid of the MANY crash reports caused by DLL not found errors.

_**This bug should be re-opened**_ as the problem is not fixed and the work-around is not really a work-around because you still CANNOT use AppCenter with .NET 5.0 and take advantage of its new features and bug fixes.

cc: @AnastasiaKubova

**Comment by Jamminroot** [comment]
Hey guys, just an update here - PR with the fix is drafted; Once work is done and PR is merged, you can expect this fix in the next SDK release.

**Comment by anti-matter** [comment]
@Jamminroot when can we expect the next release of the sdk containing the fix mentioned above?

Thank you!

**Comment by MatkovIvan** [comment]
Hi @anti-matter,
We have no specific ETA for the release yet, sorry. All I can say is that it will be in this quarter.
For now, I can suggest you build the version from `develop`. branch instead of using NuGet.

**Comment by Mgamerz** [comment]
Since it says it will be this quarter, I assume that will be within the next 3ish weeks?

**Comment by MatkovIvan** [comment]
yep

**Comment by AnastasiaKubova** [comment]
Hi there! The fix has been released in the [4.2.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.2.0) version of App Center SDK.

**Comment by HppZ** [comment]
Still have this issue.
WPF .NET5 project.
![image](https://user-images.githubusercontent.com/12285582/146768514-7e0f99a5-19dc-43eb-8498-de1b6849dea9.png)

**Comment by HppZ** [comment]
@AnastasiaKubova

**Comment by AnastasiaKubova** [comment]
Hi, @HppZ ! Thanks for getting in touch with us! Looks like your issue is related to this[ feature request](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1589). Currently, the App Center SDK doesn't support non-WinUI applications.

**Comment by HppZ** [comment]
@AnastasiaKubova  please support.

**Comment by AnastasiaKubova** [comment]
@HppZ, Currently, the App Center SDK doesn't support non-WinUI applications. You can track the progress of this feature [here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1589).
